language: python
python:
- '2.7'
- '3.4'
- '3.6'
install:
- python setup.py install
script:
- python setup.py test --addopts "-m 'not inttest' --cov=PyOpenWorm --ignore=tests/InferenceTest.py"
- python setup.py test --addopts "-m 'inttest' --cov=PyOpenWorm --ignore=tests/InferenceTest.py"
after_success:
- coveralls
- "./codespeed-submit.sh"
env:
  global:
  - secure: Qt0b8NlTnB2FxwdmlXL9/RLcDNA6gUx6+xriipLIZuv+n0rjUmovgqT1UfHGsIUl6pFUXKA8ywPoD2znd3GfigWs/VrB6fXgJiNVNPq1bx1xbX9sPl/6xw5wcVA8nDfFVMj5Q8I5qECaxUwXR83LiKrTCRGewNCRxgGj7aLiYso=
  - secure: ENKLEo8JnZG52urue+pGnJQCpsHbLTn50tONqD3weJmEjMi8Lwq3twl3Yt59VWmSkj7tRxRlCi+ORw2zhsPchvlIxcBe8xbjwcxf3J5Y0x+lw7sb28pjRGHpJS0E2dv1H/o9cEKI+QWRNgUlDS6h8oNlZaJJ+fL9W629PzikkbpkK3WWF/SsCAVDgeGbL3u2ViU85aMquUDu6WaRl8IiU/HoUzRZWQyi94RqPICdXNeF/Z58zDHdC+Sn8OtWsnfXuBs0vVTE/7yuowKiLNxeh9R7cVIi+ch6v+73jxkE6At0+jNjYLoMAtEwv2Pfwk2LItu/H3QDXnmHKzIy2WujEGhnVT0WlkaQrp18ngwVXt4OniGmvRCPR1kjQEcm85ji1QgRMXsYgEJiPiVSbaiVngJKFMp5hSf9CiszXIav5TFZJ2gZK4Pvw3YDEZaMj7TENC/dGQJjHmMk1hoNOuqbjZrVK3YjxBwd7EWVuPdtLreOA6q1m/5gMd/cYBdrB+l9dLyaZm6HibQOciAwNk7PPSwMfU9+RJVQWUvZqxZ1XSIICJypGCXU+iSVuStQ/llYtuUk2QTc16bvWXX5RK3MOYBd13XdTo6RETMrj942arAK67whVh0ewraURX0nCgzToLMEe5mUL+OpNv8OW7w6phSqM5LDcID6OOFMGTj4Qgw=
